In [45]:
import os
from PIL import Image
import plotly.express as px
import colorgram
import numpy as np
import pandas as pd
from scipy.stats import gaussian_kde

In [2]:
img_folder = os.path.join("../../","Dataset/","ZAPATOS")
img_folder

'../../Dataset/ZAPATOS'

In [3]:
imgs = os.listdir(img_folder)
len(imgs)

1220

In [4]:
imgs_sizes = []
for i in imgs:
    img = Image.open(img_folder+"/"+ i)
    imgs_sizes.append(img.size)

In [5]:
imgs_desc_dict = {}

for i, j in zip(imgs, imgs_sizes):
    imgs_desc_dict.update({i: j})

In [6]:
imgs_desc_dict

{'Salomon_X-ALP_Mid_Distressed_Leather_GTX_Dark_Earth_Black_34i.jpg': (800,
  571),
 'Bravest_Studios_Bear_Claw_Mule_Brown_owo.jpg': (800, 571),
 'adidas_F50_Elite_FG_Celestial_Victory_Pack_cav.jpg': (800, 571),
 'Nike_Offcourt_Slide_Kobe_Bryant_Dodgers.jpg': (800, 571),
 'Clarks_Torhill_Hi_Wine_Suede_ifg.jpg': (800, 571),
 'Crocs_Classic_Clog_SpongeBob_SquarePants_Squidward_k9d.jpg': (800, 571),
 'UGG_Classic_Ultra_Mini_Boot_Caribou_Womens_xuh.jpg': (800, 571),
 'UGG_Classic_Short_Boot_Hidden_NY_Sand.jpg': (800, 571),
 'Nike_Air_Max_RK61_Air_Afrique_Coconut_Milk.jpg': (800, 571),
 'Jordan_1_Retro_Low_Golf_Phantom_Volt.jpg': (800, 571),
 'Nike_Mercurial_Superfly_9_Academy_MG_Pink_Foam_Black_c22.jpg': (800, 571),
 'adidas_Taekwondo_Mei_Ballet_White_Better_Scarlet_Womens.jpg': (800, 571),
 'Crocs_Classic_Clog_SpongeBob_SquarePants_Patrick_Star.jpg': (800, 571),
 'adidas_Yeezy_Slide_Salt.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Patent_Boots_Black_kx6.jpg': (800, 571),
 'Clarks_Originals_Wallabee_Harris_Tweed_Pack_Brown_l90.jpg': (800, 571),
 'Nike_Air_Max_Phenomena_Burgundy_Crush_Black_Womens.jpg': (800, 571),
 'UGG_Tasman_Maxi_Curly_Slipper_Natural_Womens.jpg': (800, 571),
 'Nike_Mercurial_Superfly_10_Elite_FG_Mad_Voltage_Pack.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Chestnut_Womens.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Spruce_Aura_Light_Silver.jpg': (800, 571),
 'Timberland_6_Premium_Brogue_Boot_Medium_Brown_Wingtip_ptw.jpg': (800, 571),
 'Crocs_Classic_Clog_SpongeBob_SquarePants_Patrick_Star_sdq.jpg': (800, 571),
 'Nike_Mercurial_Vapor_16_Pro_TF_Glacier_Blue_Blue_Orbit_zsa.jpg': (800, 571),
 'Nike_Phantom_6_Low_Elite_FG_Kobe_Bryant_Phantom_Black.jpg': (800, 571),
 'Timberland_6_Premium_Boot_Black_Nubuck_GS.jpg': (800, 571),
 'Timberland_Premium_Waterproof_Super_Boot_Emerald_Woods_Dark_Green.jpg': (800,
  571),
 'Crocs_Classic_Clog_DreamWorks_Shrek_d61.jpg': (800, 571),
 'Bravest_Studios_Leopard_Claw_Mule_Dark_Leopard_qfi.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Beige_ekt.jpg': (800, 571),
 'UGG_Tazz_II_Slipper_Obsidian_Womens_ze5.jpg': (800, 571),
 'Jordan_Mule_Black_Metallic_Silver_Womens.jpg': (800, 571),
 'UGG_Tazz_Slipper_Hickory_Womens_u0e.jpg': (800, 571),
 'adidas_Predator_Elite_FG_Celestial_Victory_Pack_ktq.jpg': (800, 571),
 'adidas_F50_Elite_FG_Messi_Player_Pack_1_40v.jpg': (800, 571),
 'Nike_Woodside_Chukka_2_Light_Taupe_Womens_6ih.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Vapor_16_Elite_FG_Kylian_Mbapp_Pack_iov.jpg': (800, 571),
 'Ferragamo_Trezze_Heel_Sandal_Peach_Womens_h9k.jpg': (800, 571),
 'adidas_Yeezy_Foam_RNR_MX_Granite.jpg': (800, 571),
 'Balenciaga_x_Crocs_Bootie_Black.jpg': (800, 571),
 'UGG_Pumped_Slide_Mustard_Seed_Womens_ik9.jpg': (800, 571),
 'YZY_YS-01_Fudge.jpg': (800, 571),
 'Nike_Zoom_Air_Vapor_Pro_1_White_Stadium_Green_Metallic_Silver_Black_0xq.jpg': (800,
  571),
 'adidas_F50_Elite_Laceless_FG_Vivid_Horizon_Pack_708.jpg': (800, 571),
 'Nike_Mercurial_Superfly_10_Academy_AG_Ocean_Cube_Pink_Blast_yjb.jpg': (800,
  571),
 'Nike_ReactX_Rejuven8_Light_Orewood_Brown_xwg.jpg': (800, 571),
 'YZY_YS-01_Black_bna.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Superfly_9_Elite_FG_Lemonade_z0v.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Burgundy_Beige_Nubuck_h5r.jpg': (800,
  571),
 'Puma_Speedcat_Ballet_Black_White_Womens.jpg': (800, 571),
 'adidas_Taekwondo_Caroline_Hu_x_CLOT_Pink_Silver_Womens_ki1.jpg': (800, 571),
 'adidas_Copa_Pure_3_Pro_FG_Celestial_Victory_Pack_3dv.jpg': (800, 571),
 'Nike_Tiempo_Legend_10_Elite_FG_Copa_White.jpg': (800, 571),
 'Nike_Diamond_Standout_MCS_Wolf_Grey_White_Black_2vj.jpg': (800, 571),
 'Jordan_1_Retro_Low_Golf_Endless_Pursuit_Pack_luf.jpg': (800, 571),
 'Jordan_Air_Rev_White_Black_qws.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Slide_Light_Crimson_7oz.jpg': (800, 571),
 'Nike_Mercurial_Superfly_10_Elite_FG_Glacier_Blue.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Vapor_16_Elite_FG_Vini_Jr_Sunset_Pulse.jpg': (800, 571),
 'Moon_Boot_Icon_Nylon_Boot_White.jpg': (800, 571),
 'Ferragamo_Algedi_Pumps_Orange_Womens.jpg': (800, 571),
 'Nike_Air_Max_Goadome_865031_Black.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Avirex_Wheat_dah.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Dusted_Cocoa_Kids_bk3.jpg': (800, 571),
 'Jordan_1_Mid_TD_Cleat_Panda.jpg': (800, 571),
 'Nike_Mercurial_Vapor_16_Elite_FG_Scary_Good_Pack.jpg': (800, 571),
 'Nike_Air_Max_95_Golf_White_Black.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Slide_Triple_Black_Womens_rrw.jpg': (800, 571),
 'Dr_Martens_1460_Smooth_Leather_Lace_Up_Boot_Black_udo.jpg': (800, 571),
 'Nike_Manoa_Haystack_x3u.jpg': (800, 571),
 'Jordan_1_Mule_Golf_University_Blue_3dp.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Patent_Boots_Finch_Wheat.jpg': (800, 571),
 'Jordan_1_Retro_High_Golf_Bordeaux_pze.jpg': (800, 571),
 'Nike_Free_Golf_Next_Nature_White_Pure_Platinum_Wolf_Grey_Black_wf2.jpg': (800,
  571),
 'Nike_ReactX_Rejuven8_Triple_Black_Womens.jpg': (800, 571),
 'Gucci_Web_Slide_Pink_Rubber_Womens_5wd.jpg': (800, 571),
 'Crocs_Classic_Clog_Navy_hl7.jpg': (800, 571),
 'Crocs_Classic_Clog_IT_Pennywise_6kv.jpg': (800, 571),
 'Air_Jordan_5_Retro_Low_Golf_Black_Metallic_4rh.jpg': (800, 533),
 'Nike_Tiempo_Legend_10_Elite_FG_Soar_White_fyh.jpg': (800, 571),
 'UGG_Classic_Ultra_Mini_Platform_Boot_Sand_Womens.jpg': (800, 571),
 'UGG_Cozy_Slipper_Cream_Womens.jpg': (800, 571),
 'Moon_Boot_Icon_Nylon_Low_Boot_White_Black_mky.jpg': (800, 571),
 'Crocs_Classic_Cozzzy_Slipper_Reindeer.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Slide_SWOOSH_Touch_Grass_Kelly_Green.jpg': (800, 571),
 'Ferragamo_Ilary_X5_Suede_Pumps_Pink_Womens_umh.jpg': (800, 571),
 'YZY_YS-01_Black_8jo.jpg': (800, 571),
 'adidas_Ace_Mid_Moon_Boot_Silver_6f6.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Superfly_10_Elite_FG_United_Pack_9kq.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Superfly_10_Elite_FG_Attack_Pack.jpg': (800, 571),
 'Nike_Maxfly_2_Glam_Fierce_Purple_Pink_Blast.jpg': (800, 571),
 'adidas_Adizero_Electric_II_Rodeo_bjw.jpg': (800, 571),
 'Timberland_Field_Boot_Waterproof_Dark_Red_Nubuck.jpg': (800, 571),
 'Puma_Speedcat_Ballet_For_All_Time_Red_Womens.jpg': (800, 571),
 'Nike_Tiempo_Legend_10_Elite_FG_Black_Deep_Jungle.jpg': (800, 571),
 'adidas_Yeezy_Foam_RNNR_MX_Sand_Grey_4gg.jpg': (800, 571),
 'Dr_Martens_1461_3-Eye_Shoe_Supreme_Skull_Blue_Black_4ls.jpg': (800, 571),
 'Jordan_Nu_Retro_1_Low_Golf_Black_White_9i2.jpg': (800, 571),
 'Vans_Loafer_Year_of_the_Horse_Brown_s0u.jpg': (800, 571),
 'Ferragamo_Aldura_Heel_Sandals_Green_Womens.jpg': (800, 600),
 'UGG_Scuffette_II_Slipper_Chestnut_Womens.jpg': (800, 571),
 'Diemme_Roccia_Vet_Gomma_Shearling_Boot_Ronnie_Fieg_Klein_Blue_Womens_xwo.jpg': (800,
  571),
 'UGG_Tasman_Slipper_Palace_Burnt_Olive_Camo_89e.jpg': (800, 571),
 'Jordan_1_Retro_Low_Golf_Rust_Pink_hya.jpg': (800, 571),
 'Jordan_Mule_Soft_Pearl_Womens_17g.jpg': (800, 571),
 'Gucci_Ayrton_Webbing-Trimmed_Horsebit_Leather_Driver_Loafers_Black_pbe.jpg': (800,
  571),
 'UGG_Lowmel_Rocky_Oak_Womens.jpg': (800, 571),
 'adidas_Yeezy_Slide_Soot_wky.jpg': (800, 571),
 'Balenciaga_x_Crocs_Bootie_Black_Womens.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Chestnut.jpg': (800, 571),
 'Clarks_Originals_Wallabee_Boot_Beeswax_Leather_pm4.jpg': (800, 571),
 'UGG_Tazz_II_Slipper_Chestnut_Womens.jpg': (800, 571),
 'adidas_Adilette_Lumia_Slides_The_Simpsons_Court_Green.jpg': (800, 571),
 'UGG_Classic_Micro_Slipper_Dusted_Cocoa_Womens_dku.jpg': (800, 571),
 'Nike_Diamond_Turf_93_TD_49ers_3v9.jpg': (800, 571),
 'Puma_Speedcat_Ballet_Whisp_of_Pink_Womens.jpg': (800, 571),
 'Jordan_1_Retro_Low_Golf_Triple_White_dfu.jpg': (800, 571),
 'Ferragamo_Bonnie_Pumps_Blue_Womens_6xz.jpg': (800, 571),
 'adidas_Predator_Elite_Foldover_Tongue_FG_Pure_Victory_Pack.jpg': (800, 571),
 'UGG_Tazz_Slipper_Red_Jasper_Womens_32t.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Black_GS.jpg': (800, 571),
 'Nike_Calm_Slide_Black_Gum.jpg': (800, 571),
 'adidas_Adimule_Slides_Liberty_London_Bold_Green_Yellow_Womens_uj1.jpg': (800,
  571),
 'Jordan_1_Mid_TD_Cleat_Shadow_20_8tj.jpg': (800, 571),
 'Nike_Phantom_Luna_2_Elite_FG_Mad_Voltage_Pack_pte.jpg': (800, 571),
 'Bravest_Studios_Suede_Paisley_Clogs_Black.jpg': (800, 571),
 'Crocs_Classic_Clog_South_Park_Cartman.jpg': (800, 571),
 'Jordan_1_Retro_High_Golf_Black_White.jpg': (800, 571),
 'Dr_Martens_1461_Quad_Derby_Shoes_Black.jpg': (800, 571),
 'Jordan_Nu_Retro_1_Low_Golf_White_Pure_Platinum_ea9.jpg': (800, 571),
 'Nike_Air_Max_Goadome_Black_Pony_Hair.jpg': (800, 571),
 'Nike_Phantom_6_High_Elite_FG_Scary_Good_Pack_esv.jpg': (800, 571),
 'Nike_Phantom_6_Low_Elite_FG_Hyper_Crimson_Limelight_fh6.jpg': (800, 571),
 'Jordan_1_Retro_High_MCS_White_Digital_Pink_98b.jpg': (800, 571),
 'Bottega_Veneta_Bounce_Ankle_Boot_Black_Womens.jpg': (800, 571),
 'Timberland_6_Classic_Waterproof_Boot_Wheat_Mesh_Lining_0op.jpg': (800, 571),
 'Jordan_Spizike_Golf_OG_White_Classic_Green.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Vapor_16_Elite_FG_Fear_Nothing_Pack.jpg': (800, 571),
 'Nike_Mercurial_Superfly_10_Academy_FGMG_United_Pack_j9j.jpg': (800, 571),
 'UGG_Classic_Mini_Platform_Boot_Black_Womens_mnc.jpg': (800, 571),
 'Nike_Calm_Mule_SE_Sanddrift_Fur_Womens_j8y.jpg': (800, 571),
 'Gucci_Slides_Bloom_Supreme_idu.jpg': (800, 571),
 'UGG_Lowmel_Meadow_Sand_Castle_Womens_6rv.jpg': (800, 571),
 'YZY_YS-01_Black_d8p.jpg': (800, 571),
 'Nike_Mercurial_Vapor_16_Elite_FG_Mad_Voltage_Pack_aox.jpg': (800, 571),
 'Nike_Superfly_Elite_2_Bright_Crimson_Lime_Blast_Mint_Foam_Washed_Coral.jpg': (800,
  571),
 'Birkenstock_Arizona_Natural_Leather_Concrete_Gray_f0u.jpg': (800, 571),
 'UGG_Devandra_Tall_Boot_Walnut_Womens.jpg': (800, 571),
 'Givenchy_Paris_Slide_Sandals_Black_eif.jpg': (800, 571),
 'adidas_F50_Elite_FG_Road_to_Glory_Pack_qg2.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Caribou_Sapphire_Ice_Womens.jpg': (800, 571),
 'Bravest_Studios_Bear_Claw_Mule_Purple_gkk.jpg': (800, 571),
 'Nike_Premier_3_TF_Black_White_ss9.jpg': (800, 571),
 'Nike_Mercurial_Vapor_16_Pro_TF_Black_Deep_Jungle_h9g.jpg': (800, 571),
 'UGG_Tazz_Slipper_Black_Womens_4ex.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Slide_SWOOSH_Touch_Grass_Wheat_f8b.jpg': (800, 571),
 'UGG_Zora_Ballet_Flat_Chestnut_Womens.jpg': (800, 571),
 'adidas_F50_Elite_FG_Messi_Miami_lhu.jpg': (800, 571),
 'New_Balance_1906L_Raincloud_p75.jpg': (800, 571),
 'Timberland_6_Premium_Vibram_Gore-Tex_Boot_Dark_Grey_jbz.jpg': (800, 571),
 'Bravest_Studios_Bear_Claw_Mule_Brown_yj8.jpg': (800, 571),
 'Puma_Speedcat_Ballet_White_Black_Womens_ief.jpg': (800, 571),
 'Crocs_Pollex_Clog_by_Salehe_Bembury_x_Kenny_Scharf_Art_Friends_Thumbs_Up_Good_Job_x9u.jpg': (800,
  571),
 'adidas_Yeezy_450_Slide_Cream_5fj.jpg': (800, 571),
 'UGG_Classic_Mini_II_Boot_Dried_Oregano_Womens.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Wheat_Womens.jpg': (800, 571),
 'Crocs_Classic_Clog_SpongeBob_SquarePants_Patrick_Star_zo8.jpg': (800, 571),
 'Jordan_Super_Play_Slide_J_Balvin.jpg': (800, 571),
 'Nike_Air_Rift_Fir_Metallic_Gold_Womens.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Dark_Grey.jpg': (800, 571),
 'adidas_Superstar_Boot_Thug_Club_Black_White_sfh.jpg': (800, 571),
 'Nike_Tiempo_Ligera_Pro_FG_LE_Metallic_Red_Bronze_Rose_Gold.jpg': (800, 571),
 'adidas_F50_Elite_Laceless_FG_Radiant_Blaze_Pack_od3.jpg': (800, 571),
 'Nike_Diamond_Showcase_MTL_Wolf_Grey_White_Black_r9e.jpg': (800, 571),
 'Nike_SFB_Air_Field_Ukiah_8_Gore-Tex_Black_9v1.jpg': (800, 571),
 'UGG_Classic_Micro_Sand_Womens.jpg': (800, 571),
 'Nike_Air_Rift_Black_Metallic_Silver_Womens.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Supreme_Multi-Color_hch.jpg': (800,
  571),
 'UGG_Tasman_Slipper_Palace_x_Looney_Tunes_Yellow_jub.jpg': (800, 571),
 'Birkenstock_Boston_Suede_Thyme_6mo.jpg': (800, 571),
 'Birkenstock_Arizona_Birko_Flor_Black_Black_Foot_Bed.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Sand_Dark_Cherry_Womens.jpg': (800, 571),
 'Nike_Vapor_Edge_Speed_360_2_White_Metallic_Silver_pdz.jpg': (800, 571),
 'Birkenstock_Boston_Big_Buckle_Nubuck_Sandcastle_nux.jpg': (800, 571),
 'Birkenstock_Boston_Essentials_EVA_Black.jpg': (800, 571),
 'Bravest_Studios_Foot_Clog_Green_gd4.jpg': (800, 571),
 'Nike_Mercurial_Superfly_10_Academy_FGMG_Kylian_Mbapp_Grand_Purple_kg9.jpg': (800,
  571),
 'Nike_Mercurial_Superfly_10_Academy_AG_Volt_Black_ime.jpg': (800, 571),
 'adidas_Yeezy_Foam_RNNR_Vermillion.jpg': (800, 571),
 'Gucci_Web_Slide_Pink_Rubber_Womens.jpg': (800, 571),
 'adidas_Yeezy_Slide_Onyx.jpg': (800, 571),
 'Birkenstock_Mayari_Birko-Flor_Black_do2.jpg': (800, 571),
 'adidas_F50_Elite_FG_Radiant_Blaze_Pack_wmd.jpg': (800, 571),
 'adidas_Yeezy_Foam_RNR_Stone_Salt.jpg': (800, 571),
 'Bravest_Studios_Bear_Claw_Mule_Red_wje.jpg': (800, 571),
 'Crocs_Classic_Clog_Xbox_6cc.jpg': (800, 571),
 'UGG_Goldenstar_Clog_Black_Womens_6rn.jpg': (800, 571),
 'Crocs_Classic_Cozzzy_Sandal_Monsters_Inc_Sulley.jpg': (800, 571),
 'Nike_Phantom_6_Low_Elite_AG-Pro_Hyper_Crimson_Limelight_t12.jpg': (800, 571),
 'Bravest_Studios_Foot_Clog_Green_llu.jpg': (800, 571),
 'Nike_Air_Rift_Leather_Metallic_Silver_Sail_Womens.jpg': (800, 571),
 'Nike_Tiempo_Legend_10_Elite_FG_Fear_Nothing_Pack_669.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Wheat_Debossed_Print_1ol.jpg': (800,
  571),
 'Nike_Phantom_Luna_2_Elite_FG_Metallic_Gold_Coin_lat.jpg': (800, 571),
 'UGG_Lowmel_Meadow_Horizon_Pink_Womens_ae4.jpg': (800, 571),
 'Birkenstock_Boston_Soft_Footbed_Suede_Taupe.jpg': (800, 571),
 'UGG_Classic_Mini_II_Boot_Black_Womens.jpg': (800, 571),
 'Nike_Phantom_6_High_Elite_FG_Hyper_Crimson_Limelight_r2a.jpg': (800, 571),
 'adidas_Yeezy_Foam_RNR_MX_Cinder.jpg': (800, 571),
 'Nike_Phantom_6_Low_Elite_FG_Attack_Pack_ck0.jpg': (800, 571),
 'Nike_Phantom_6_High_Elite_AG_Scary_Good_Pack_30r.jpg': (800, 571),
 'Birkenstock_Arizona_Birko-Flor_Dark_Brown.jpg': (800, 571),
 'adidas_Yeezy_Foam_RNR_MX_Carbon_nr0.jpg': (800, 571),
 'Bottega_Veneta_Bounce_Ankle_Boot_Black_Womens_8kt.jpg': (800, 571),
 'adidas_Predator_Elite_Fold-Over_Tongue_FG_Coral_Blaze_Pack.jpg': (800, 571),
 'New_Balance_1906L_Rich_Oak.jpg': (800, 571),
 'Nike_Air_Max_Cirro_Slide_Black_Metallic_Silver_cp6.jpg': (800, 571),
 'Nike_Air_Max_95_Golf_Peony_Dusty_Cactus_e86.jpg': (800, 571),
 'Crocs_Classic_Clog_Coca-Cola_Diet_Coke.jpg': (800, 571),
 'Bravest_Studios_Bear_Claw_Mule_Purple.jpg': (800, 571),
 'UGG_Classic_Ultra_Mini_Weather_Hybrid_Boot_Mustard_Seed_Summer_Wheat.jpg': (800,
  571),
 'Crocs_Classic_Clog_South_Park_Kenny.jpg': (800, 571),
 'Crocs_Classic_Clog_Disney_Minnie_Mouse.jpg': (800, 571),
 'UGG_Classic_Ultra_Mini_Boot_Sand_Womens.jpg': (800, 571),
 'Birkenstock_Arizona_Birko-Flor_Stone_Coin.jpg': (800, 571),
 'Dr_Martens_Adrian_Arcadia_Leather_Tassel_Loafer_Cherry_Red_mox.jpg': (800,
  571),
 'Nike_Zoom_Mercurial_Vapor_16_Elite_FG_Kylian_Mbapp_Grand_Purple.jpg': (800,
  571),
 'Nike_Zoom_Mercurial_Superfly_10_Elite_FG_United_002_Pack_6ma.jpg': (800,
  571),
 'UGG_Tazz_II_Slipper_Cobble_Grey_Womens.jpg': (800, 571),
 'adidas_Yeezy_Slide_Slate_Grey.jpg': (800, 571),
 'Birkenstock_Arizona_Soft_Footbed_Suede_Mink.jpg': (800, 571),
 'Timberland_6_Premium_Boot_Black_Nubuck_PS_5l1.jpg': (800, 572),
 'Puma_Speedcat_Ballet_Black_Mauve_Mist_Womens.jpg': (800, 571),
 'Crocs_Classic_Clog_Disney_Goofy.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Rust_Full_Grain_Dark_Grey.jpg': (800,
  571),
 'UGG_Classic_Short_II_Boot_Black_Womens_gx7.jpg': (800, 571),
 'UGG_Classic_Mini_Platform_Boot_Chestnut_Womens_3ab.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Superfly_10_Academy_FGMG_United_002_Pack_ota.jpg': (800,
  571),
 'adidas_Adimule_Slides_Liberty_London_Sandy_Pink_Green_Womens_trt.jpg': (800,
  571),
 'adidas_Predator_Elite_Fold-Over_Tongue_FG_Unlocked.jpg': (800, 571),
 'New_Balance_1906L_Neon_Silver_Metallic.jpg': (800, 571),
 'UGG_Tasman_II_Slipper_Dusted_Cocoa.jpg': (800, 571),
 'Nike_Rift_Mesh_SKIMS_Black_Womens.jpg': (800, 571),
 'Jordan_1_Retro_High_Golf_Patent_Midnight_Navy.jpg': (800, 571),
 'Bravest_Studios_Foot_Clog_Green_9nt.jpg': (800, 571),
 'Nike_Phantom_GX_2_Elite_AG_Prism_Pack_trz.jpg': (800, 571),
 'Bravest_Studios_Bear_Claw_Mule_White_2bj.jpg': (800, 571),
 'Ferragamo_Eva_55_Patent_Leather_Pumps_Bluette_Womens.jpg': (800, 571),
 'Timberland_Field_Boot_Lace_Up_Waterproof_Black_lb1.jpg': (800, 571),
 'Timberland_6_Premium_Boot_Wheat_TD.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Black.jpg': (800, 571),
 'UGG_Zora_Ballet_Flat_Dusted_Cocoa_Womens_fto.jpg': (800, 571),
 'Converse_1908_Bronco_Boot_GOLF_le_FLEUR_Tyler_The_Creator_Emperador_3k9.jpg': (800,
  571),
 'Nike_Air_Max_Goadome_Sail_Cacao_Wow_Cow_Print_Pony_Hair.jpg': (800, 571),
 'New_Balance_442_Elite_Knit_FG_V3_First_Edition_8e4.jpg': (800, 571),
 'Nike_Air_Max_90_Golf_Silver_Pine_Bicoastal_kms.jpg': (800, 571),
 'Christian_Louboutin_Take_It_Easy_Flat_Goose.jpg': (800, 571),
 'Nike_Calm_Slide_Flat_Pewter.jpg': (800, 571),
 'Nike_Air_Max_1_86_OG_Golf_Wolf_Grey_Bright_Cactus_177.jpg': (800, 571),
 'Crocs_Classic_Clog_SpongeBob_SquarePants_Squidward.jpg': (800, 571),
 'Crocs_Classic_Crush_Clog_Bone_4ia.jpg': (800, 571),
 'UGG_Lowmel_Black_Womens.jpg': (800, 571),
 'Jordan_1_Retro_High_Golf_Metallic_Green.jpg': (800, 571),
 'Nike_Infinity_Tour_2_Gore-Tex_Black_6cf.jpg': (800, 571),
 'adidas_F50_Elite_AG_Road_to_Glory_Pack_g2o.jpg': (800, 571),
 'adidas_Predator_Elite_Foldover_Tongue_FG_Stealth_Victory_Pack_ccl.jpg': (800,
  571),
 'Nike_Air_Max_Cirro_Slide_Triple_Black_5he.jpg': (800, 571),
 'Birkenstock_Boston_Essentials_EVA_Faded_Khaki_xn0.jpg': (800, 571),
 'Birkenstock_Arizona_Birkibuc_Stone.jpg': (800, 571),
 'adidas_Superstar_Dress_Shoe_CLOT_by_Edison_Chen_Cow_Print.jpg': (800, 571),
 'UGG_Classic_Mini_Bow_Boot_Sand_Womens_7gz.jpg': (800, 571),
 'Nike_Air_Max_1_86_OG_Golf_White_Black_Gum.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Green_Strike.jpg': (800, 571),
 'Nike_Phantom_Luna_2_Elite_FG_Pink_Foam_gup.jpg': (800, 571),
 'Nike_Air_Zoom_Maxfly_Racer_Blue_Lime_Blast_1uu.jpg': (800, 571),
 'Nike_Phantom_Luna_2_Elite_FG_Mad_Energy_Pack_6u8.jpg': (800, 571),
 'Nike_ACG_Rufus_Sequoia_00q.jpg': (800, 571),
 'Diemme_Roccia_Vet_Shearling_Boot_Ronnie_Fieg_Wheat_Womens_udl.jpg': (800,
  571),
 'UGG_Tasman_II_Slipper_Driftwood_Biking_Red_w0r.jpg': (800, 571),
 'UGG_Classic_Ultra_Mini_Boot_Palace_x_Looney_Tunes_Black_z1x.jpg': (800, 571),
 'Birkenstock_Boston_Shearling_Taupe_qht.jpg': (800, 571),
 'Nike_Phantom_6_High_Elite_FG_Kobe_Bryant_Phantom_Black.jpg': (800, 571),
 'Crocs_Classic_Lined_Clog_The_Grinch_vpb.jpg': (800, 571),
 'adidas_Taekwondo_Mei_Ballet_Clear_Pink_White_Womens.jpg': (800, 571),
 'Burberry_TB_Logo_Plaque_Ballerina_Flat_Black_Womens.jpg': (800, 572),
 'Crocs_Classic_Cozzzy_Slipper_Reindeer_29x.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Vapor_16_Elite_FG_Dj_Vu_1jc.jpg': (800, 571),
 'UGG_Scuffette_II_Slipper_Sand_Womens.jpg': (800, 571),
 'Birkenstock_Boston_Soft_Footbed_Suede_Mocha.jpg': (800, 571),
 'Nike_Phantom_6_Low_Elite_FG_Hyper_Crimson_Limelight.jpg': (800, 571),
 'Crocs_Classic_Clog_Monsters_Inc_Mike_Wazowski_6te.jpg': (800, 571),
 'UGG_Tazzlita_Slipper_Chestnut_Womens_lcl.jpg': (800, 571),
 'UGG_Tasman_Slipper_Black_a6m.jpg': (800, 571),
 'Nike_Zoom_Mercurial_Vapor_16_Elite_FG_Dream_Speed_Pack_b2g.jpg': (800, 571),
 'adidas_Yeezy_Slide_Bone_20222023_Restock.jpg': (800, 571),
 'Diemme_Roccia_Vet_Gomma_Shearling_Boot_Ronnie_Fieg_Bordeaux_9ck.jpg': (800,
  571),
 'Jordan_1_Retro_High_Golf_University_Blue.jpg': (800, 571),
 'Nike_ACG_Moc_Premium_Sail_Neutral_Olive_Apricot_Agate_Baroque_Brown_kr3.jpg': (800,
  571),
 'Crocs_Classic_Bootlegger_Slide_Luke_Combs_Black.jpg': (800, 571),
 'adidas_Predator_Mania_FG_LE_Gunmetal_6tf.jpg': (800, 571),
 'Timberland_6_Premium_Waterproof_Boot_Wren.jpg': (800, 571),
 'Crocs_Classic_Clog_Back_to_the_Future_4jv.jpg': (800, 571),
 'adidas_F50_Elite_FG_Messi_Prestig10_Pack_jmv.jpg': (800, 571),
 'Nike_ReactX_Rejuven8_Slide_Black.jpg': (800, 571),
 'Jordan_1_Retro_Low_Golf_Wolf_Grey.jpg': (800, 571),

In [7]:
df = pd.DataFrame(imgs_desc_dict).T
df.rename(columns={0: 'Width', 1: 'Height'}, inplace=True)

df

                                                    Width  Height
Salomon_X-ALP_Mid_Distressed_Leather_GTX_Dark_E...    800     571
Bravest_Studios_Bear_Claw_Mule_Brown_owo.jpg          800     571
adidas_F50_Elite_FG_Celestial_Victory_Pack_cav.jpg    800     571
Nike_Offcourt_Slide_Kobe_Bryant_Dodgers.jpg           800     571
Clarks_Torhill_Hi_Wine_Suede_ifg.jpg                  800     571
...                                                   ...     ...
Crocs_Pollex_Clog_by_Salehe_Bembury_Cobbler_w1f...    800     571
adidas_Yeezy_Slide_Slate_Marine_Kids_sp8.jpg          800     571
adidas_F50_Elite_FG_Mo_Salah_The_Egyptian_King_...    800     571
Nike_Phantom_GX_2_Elite_FG_Mad_Voltage_Pack_rqj...    800     571
adidas_F50_Elite_FG_Bape_Multi_Camo.jpg               800     571

[1220 rows x 2 columns]

In [ ]:
imgs_color_profile = []

for i in imgs:
    img = Image.open(img_folder+"/"+ i)
    colors = colorgram.extract(img, 3)
    
    for j in colors:
        r = j.rgb.r
        g = j.rgb.g
        b = j.rgb.b

    imgs_color_profile.append([r,g,b])

Processing images: 100%|██████████| 1220/1220 [12:23<00:00,  1.64it/s]

In [13]:
df['icp'] = imgs_color_profile
df['icp_u'] = [np.mean(profile) for profile in imgs_color_profile]

In [14]:
df

,Width,Height,icp,icp_u
Salomon_X-ALP_Mid_Distressed_Leather_GTX_Dark_Earth_Black_34i.jpg,800,571,"[48, 49, 52]",49.666667
Bravest_Studios_Bear_Claw_Mule_Brown_owo.jpg,800,571,"[119, 79, 57]",85.000000
adidas_F50_Elite_FG_Celestial_Victory_Pack_cav.jpg,800,571,"[129, 143, 172]",148.000000
Nike_Offcourt_Slide_Kobe_Bryant_Dodgers.jpg,800,571,"[83, 106, 187]",125.333333
Clarks_Torhill_Hi_Wine_Suede_ifg.jpg,800,571,"[82, 20, 27]",43.000000
...,...,...,...,...
Crocs_Pollex_Clog_by_Salehe_Bembury_Cobbler_w1f.jpg,800,571,"[180, 87, 25]",97.333333
adidas_Yeezy_Slide_Slate_Marine_Kids_sp8.jpg,800,571,"[162, 157, 148]",155.666667
adidas_F50_Elite_FG_Mo_Salah_The_Egyptian_King_eeq.jpg,800,571,"[186, 149, 127]",154.000000
Nike_Phantom_GX_2_Elite_FG_Mad_Voltage_Pack_rqj.jpg,800,571,"[209, 239, 120]",189.333333
adidas_F50_Elite_FG_Bape_Multi_Camo.jpg,800,571,"[132, 164, 186]",160.666667

In [15]:
# Plotly Shape Profile 
fig = px.scatter(
    df, 
    x="Width", 
    y="Height", 
    hover_name=df.index, 
    color="icp_u"
    )
fig.update_layout(coloraxis_showscale=False)
fig.show()

In [44]:
df["Width"].value_counts(), df["Height"].value_counts()

(Width
 800    1220
 Name: count, dtype: int64,
 Height
 571    1198
 572      10
 600       8
 991       3
 533       1
 Name: count, dtype: int64)

In [16]:
df[['Red','Green','Blue']] = pd.DataFrame(df['icp'].tolist(), index=df.index)
df.head()

,Width,Height,icp,icp_u,Red,Green,Blue
Salomon_X-ALP_Mid_Distressed_Leather_GTX_Dark_Earth_Black_34i.jpg,800,571,"[48, 49, 52]",49.666667,48,49,52
Bravest_Studios_Bear_Claw_Mule_Brown_owo.jpg,800,571,"[119, 79, 57]",85.000000,119,79,57
adidas_F50_Elite_FG_Celestial_Victory_Pack_cav.jpg,800,571,"[129, 143, 172]",148.000000,129,143,172
Nike_Offcourt_Slide_Kobe_Bryant_Dodgers.jpg,800,571,"[83, 106, 187]",125.333333,83,106,187
Clarks_Torhill_Hi_Wine_Suede_ifg.jpg,800,571,"[82, 20, 27]",43.000000,82,20,27

In [18]:
# Plotly Color Profile
fig = px.scatter_ternary(df,a="Red", b="Green", c="Blue",color="icp_u", hover_name=df.index)
fig.show()

In [55]:
sum_cols = df["Red"] + df["Green"] + df["Blue"]
mask = sum_cols > 0
df_clean = df[mask].copy()

a = df_clean["Red"] / sum_cols[mask]
b = df_clean["Green"] / sum_cols[mask]
c = df_clean["Blue"] / sum_cols[mask]

x = b + c/2
y = (np.sqrt(3)/2) * c

valid_mask = np.isfinite(x) & np.isfinite(y)
x = x[valid_mask]
y = y[valid_mask]
df_clean = df_clean[valid_mask]

xy = np.vstack([x, y])
kde = gaussian_kde(xy)(xy)
df_clean["density"] = kde

fig = px.scatter_ternary(
    df_clean,
    a="Red",
    b="Green",
    c="Blue",
    color="density",
    hover_name=df_clean.index,
    color_continuous_scale="Viridis"
)

fig.update_layout(coloraxis_showscale=False)

fig.show()

fig.write_html("ternary_density.html")